### ISSUE TITLE
SyntaxError: The only valid numeric escape in strict mode is '\0' on Safari

### ISSUE THREAD

**Issue by go1t** [chilloutman/prettier-standalone#1]
I just noticed that on Safari, there is this script error `SyntaxError: The only valid numeric escape in strict mode is '\0'`. This is the first time I have seen this in anything. Do you aware of an easy fix for this? 

Thanks for this standalone version!

**Comment by chilloutman** [comment]
I've seen this too. I wasn't able to track it down yet.

**Comment by chilloutman** [comment]
Version `1.3.1-0` should now work in Safari.

The problem was babel and webpack inserting `"use strict"` in various locations. The `typescript` dependency uses uses `\1` and `\2` in a few places which doesn't work in strict mode.

**Comment by go1t** [comment]
Thanks @chilloutman I appreciate it!
