### ISSUE TITLE
Does this project still work? :)

### ISSUE THREAD

**Issue by bvaughn** [chilloutman/prettier-standalone#2]
Hi! 😄 

Just curious how you're using this library.

Loading it via a <script> tag doesn't seem to actually expose a `prettier` global (or a `prettier-standalone` global).

It also doesn't look like the bundle has been minified, which is especially important since it's huge. Any example uses you could point me to?

**Comment by chilloutman** [comment]
The `bundle.js` is a "Webpack Universal Module", which is why there are no exposed globals. You can consume it with Webpack; and I believe that CommonJS `require` should also work.

I used it with [Webpack](https://webpack.js.org) / [create-react-app](https://github.com/facebookincubator/create-react-app) and an import like this:

```js
import * as prettier from 'prettier-standalone'
```

---

I'm not actively working with it, but you can see it working on [illuminatejs.com](illuminatejs.com), where it's used to format the code you type in, in addition to the main de-obfuscation thing it does.

As for the size, there is not much that can be improved. If you do use Webpack, `prettier-standalone` can be minified along with the rest of your bundle. For example, the main JS bundle for IlluminateJS, which includes a bunch of additional dependencies, comes in at less than 4 MB, which is still a lot, but less than the 5.5 MB `bundle.js`.

`prettier` has numerous dependencies, some of which are quite large. It's safe to say that using `prettier` _in the browser_ is not ideal. It's also explicitly not a supported use-case. But hey, if you're just doing some research, like I was, or trying to build something cool but not-so-serious, this should work fine.

**Comment by bvaughn** [comment]
Thanks for the explanation! :smile: The name "standalone" suggested that might _potentially_ support a UMD context so I thought I'd ask for clarification. 😄 

 > `prettier` has numerous dependencies, some of which are quite large. It's safe to say that using `prettier` _in the browser_ is not ideal. It's also explicitly not a supported use-case. But hey, if you're just doing some research, like I was, or trying to build something cool but not-so-serious, this should work fine.

I was initially looking to use this module for [the upcoming Babel REPL](http://localhost:3002/#?babili=false&browsers=&builtIns=false&code_lz=PTAEAEDMBsHsHcBQiCWBbADrATgF1AN6gDGAzqaAL6iTaxqgDkA5tAIZo6MDcqmO-AEoBTNsXy16TbKPE8-WPKADCsACbCAsimx1sABTYA7YdBp0GjAHTBVG7bpyGT0eekVDhGaAHkMuFFgjCklLGxFvPwCg0jd-JQBlXBw2ZmEE4WwANxRiYXMpa2AklLSM7NzhOI9QAFVsFFqA6BCLJht6xubY3ncBEnoMFGh80PbgYkHhqt74_Dg2NX1oAFdmFCMCsOAFpdX1o2r-gkRQUGEjLP0ZUmFcVSNIFGYAGlPQbzWNh6fmUjezhgbndll8jD9nv93tgVkYAmhhPpYNAAJ5PaDQCHMRDUMZFUEHLFHJQnM4XLJYgAqsEpbGwaVwpCSDSMr3eu30mVIKFIuGEaiSbD5AIGj2eAEFdGwUdTBXzNGwMCLJmLmLLcELhCKMFyeXyBRq-dSAKKXLE4rbjGTeJrDHoKY6gBFqFBsKiWoq8lEje0OpS4FE6wjvABCbAARqZrsJboyRaaKUFfiKCRs5Vr3qmjOmFRgLXibAGdb6i_lrrAMBQALyESi8UugdOgGukgYaABcoF5LLZZ0mmGmak7AH5uxtewMByNjY5sCOZ3oReSsZ2E1il5do7H052s-ml1k2NAFzh57ORdANsIAOrYRWd8OwZGiIza_YbUi79_Zw1aRXa4FGS_MEc3_aFYXhRFkTRYZoB3UA91_HFeEQEBQEpHwABEfEbAALBBzkuD5vwoS9eVAAAKcM2FuNRQCCEgVl0C58FjAJWVIABKUAUEgUANHDNYeIoC4IxGNRkGEAAPGoNEgNgVmgfBiHYchQAiMxpL5Iw1AoEQxFwKxVH4Ew4WDM5eSFXJ-OEeTFNwctK2bcyzhsuylIANSPFZhE7RhGHeOtkEBOhK13ULSF4Czf07dMULOAB9IwVjQAAZWBFnHLNq1AAAGeLRW7FZxBwCigQrT8EIil5RT5KTcE7YwUW41sLJWHVsDK6raq0ziCr7GJ8A67leX5Jsaw5XVRoNTUKL64LXJVci5IUpTsuc1rXMYajw2GFAAFpLJ0o8giqTthr1MbfysHa9pFVyPhkXAAkyc6pv1dMrCBO4Xuwd4ziC_7CvwFb7K3O4crK96rs1L7AIoAAfBGmBjAAmXKAEYAFYXhkAyXkstJ9tRxhOKBs4rFIbwUFwCjGBeUnydAKwZDUYrhAoijWfZtQaoAa2EZrmwAPhch6zm5vI1AAbQAAx20x9u-2N9oAEgIAWUUoWWAF1nNwGFhCi8WJbuJjNkl_ljYeygaoISh5qBpb8GXJNnmci7pvTE0zTd5goewEaPt_R2Hudrtfw2pnJg7D5oZmvkrBjjMTf7IZxM7ZKMXuxapmnWdM8U6Ac7JX3VRLwirkA-CVV-dVZqZ0uq5jO510byusSsHkE3B3BTTE_kmc4ivhEPY8C9ALPi6Zy8TFve848Dy6E-EKxZ5vO8lSZz4Dkq2uJSlGVYFAjAyu_LF_jc1aHJI4ft_hzt9-YSU7yPk-upbm-wQvmrQbW-G74mxhHCdAUFUTojgjFUUddj6_gou3YBkEkTgNgm3E2gJ46fVHt5TUQ8gaAwergXCPJKaRxbEzKwlDLLCgoZQohJCEpp2mAHIOMNE7JxqtQ4QZMbb9VAGhdKixQBNWImsfaH5CIDzouGFEoAACOPlsCyIwHSDgpAgb0NIFYRhuFhDED5gAMRwLUIwux-TZTmsbSgC0ZA6UyHNMWwMI6an1sQrRXC-HhwrNEYIUcTbr3nhgIYrJOxcLXleQJ-C-FPXNpRJmAAeF0WQSCqVIAAOQ4MIKsBAvQ-hZl4aAlBhbt3iRpKIgRgjtz7KkjJCJsm5JjFYbxFTSCqFWGgIw1j0GuVdqqep11em_C6d0yuvd0z9NhuSMZv5hndICZvCZid5mKlmegneaZfyLNXus4IqyTbKzuOMnJ10DmMj2eLRBoDkEwQxFibJlyETXIgVic5D0HlgJuZAzUWyWYQSudBCB6ZXmuWSMwVgwge7Vx-uObJmjtGgvBZCz-GRnrjmBWcBFIwUXsWYLCtx8LYBgqxdC1kwLgDFJKUklJNF0mZP6d6RpKiXCkCKVU0A8S7BaB0HoZwpg2XVJpbUrJxyGVaOTg4HlxhTDotzhoH5ycZVklnPKvOELZyKvouCXCxg0h4oYe1NQmpOUauaTEbJprdlsvJWyjl6guWzl5dAfl1LyBCvpXk8V3KnBSsKc65OKqpz8g1ZkPQPzsHjz0Ca_wLTzXRpiDK613T4nACScUk2ybU1A3mgDBaOi9GGOMaYjKGg9hglIA4za4dNpNzQeLKZ1dfwVx2VCIBfzHkAtgumfBriSEeIWmcNC4pyApXyEeMwf8hrw2ETIUA1EBZ0Q2MkWdEZFZHUNXAEwVggZoWvPkPGGJZFBFRJPYQ_JQBLvgDgJRwjHwrCGiRLdD1IA4EouHTWPFNjNpatHQaoiDgexItLTWOs-FnF4pRHZXdSD93DOJUAAAyeDoAACEkGeSCJLQhpDqHvxQYw-Ob93S4VJRSvh1k2UADUFHQOuQ5N-M-YJOHFTyGpKsotq3i2I8lNKxasokX2vtGjD1wMUWQ6QZjMYuKOKI_i7ccCuEi0ohx7pzbnUO2zSM6xVqwA-CMHkYRGI_0SO1VkfIkYLigDMbzUAMh9pMJGG2VebKRNcdI7x8jJFmxVhrLlQjIyMX4oSgao1dqKJwrCcnDT3TgUO2tq5VZWmHpoTDJGMwXM23cI-B2wzPJLN0jSHFtCABJXAjAKBHtkSYfkZ7wPwCqDOgyKwx2yOknou945z26MnOnM9ydH2uTQphWymRLPueYDxfAsIfQUAAEThqa3yGbwlJGwf5P1sDfF0sgPbSgjEn1u5GCkVhlD7ynmduuuh4t_I_MPTo2CLbSDstfOFJRbibHpO0buOcMeJ5sDOSnkJ_hYA0mwBPWepdMh7OjvwJorLi64tJbAAAKRWORebLiiH5E4ORSHLFj1Q7on19uBtZHKYG2AGMs9cD7RdKQAe-0TD1X2uvNl4awuyeugTqL4tqDECFMQXClEQ04Bu-g8Nv3nLC-wAj-L_bxZoREPtWxGg_sUVHhZ8DRhQdS-4ku4LfJOv5HYKl0bmVWSHWusT2Thy4FEHF7OKg3OAbc8S-T0AKXTAo0uIwR6n9lvsHpEbbdOnTGyN2BNnifEaZldnaei2wgFExn1OtyPQuy6_Cg0i2MMG4OIZQ_W5FF3SAYeux9u7Bw1ebgbZqGqDj3tk7QpSNxvvYzLa1_gQSwx8CLtBx7swa6TomH4j5c9oOaYUG5AALyc905LtkcD5DqyQYwoBUf5BpqAJfVW6JLuktTYgNNj0yHWKNP7NMU8PXgBsNQCArB9_ySfvkBhAJ03JPTUZ1fE6QYnaHdBxH9fCCcrs69qc52pO6O5xbDKu6MKqrOQUTJyhIGzjicJQLphvbsZOy_p27p7uzUA1h9qYHBCTqfykAvzSg9paIJSnKkDUhkEogURcK_4DREHLq7SXjORhLNrSzbQRh7QW7GDrqnSMAgZAwia3SXiZ6HarZ0R57iEoB4ZXZqCi4hQkF0FfSo64R0xyGkyQFy4iaDLPCSHNzZ5SG55IZhIF5yawyXaLCl4cbhwaiB6MgbRBQmz6E4HMA3R0DwC3CBzKEgr5YQxeEIC-E5QGGeHhjeGhFsqUzUy0z0yMz-ZWBoCKgURjwj7vbpGrxIFoBzQ8IjJWDohP5pHeT5CZGlHgHnLuGJiqiZ4jDiB0BGA552HE6BGMhWCmB6IGwMQ1jhEdH1HdFGAy5VGbZ9E8gg4aDNFKEfYYptFaJa4aCS4eFWALFB4myu5hy_rkjlIxB-LoJr4hgrBd5FbBCdjyQtBahA7oRYQ4To4G6yFHFKQnHqJEZzFMwELizUFqEYAaEUTcFv41TbFxrBA6wu5y4xLYCbBQ7wF2p2xMx3G-TtxhKnZPb7bQamFnqIZInXQom7bParw2ElpNoPwt4Qx0HEnQqQAoiIGwzNpwzQqZCSFSL4IaYfFUHwy1AYCGofQ25GpjrUT6JwHoGOLEYC75pGLYAmJWYWLc7_5ckhYaDAHuKgEaCskFTskkG0GHwMGoFkKdYgGaicSdh969wUCVpYGknOF4HOJ8jRJmyQmgA-DhgABWXRVgms5a1B-RD0hRXe9i76721BQGgsOsTJ0hx2QZwGChthShFCKRp8AZoskZIZScfsa8K60ArJuamK6QJK42NYFEh2CIiBPYNUB2UiD4T4Iwxgwpm04WvJfIOpLi9eP6LBRAzaNU1BNUuJnyTY1pBBbhm2RZZR3mTACs0ASsT2pMMxNmGWZ2e2ReUxzk5Z0hgOEJmwZOEsc5qJSE0Wwx5wFxqeTZic2qpAPg8ARgjkmQAYhZmSnE_hpsuAsSm5oA0sw5OsnYK54k7crhPOB5twR5dJp555l5oU159Bw595M5XB75YZcGNYX5Vscuby9pG5bKqme57x_56-m21BVgwFF5V5eAEFd5D5lppAb5mSoZiFdECF6JUia5qFM5KhsYLx6Cv5Ns-CNUxG1BnJ3JY0DZgB_JYgfMap2ZhKiKVeyKeZcBw5JZyBoAWRjURgQsLZhC1uuA6Y8CJsCm72FEZO4RnYL5lCpCkyHhFcD0lFCIH5ilpRP57xgCnGgWvF8pPJmlv4ygwl-iWaVi6pABnKcBCBEcPYtZGiGlWlulosopqqMJGgKBhp3Fzl70aBvluans7lzZr2im5pbZHcfsnZnm1p4Wv4niv6Xxh8FB2i1BWpr8licu4cchlVnBgGPBbBB0A-G6VQIhwmm2chcFLR-y8M3xvxrVe0Oh-CehoxyxB2xhdwUx_h5Vr86hpAmhjAb-YJhB5EulH2ch50LVch_Bx0nVwh_VvMTMkRIRXInYfRF1PhXIFcneTxpxNAR4twNUjeNxjY7UNQsOMAqQP6scxVsMHCTMAkawZxr1lxH12EX1QS_Qv17A2IJsCJnYQNicPZgKi5GJZ1yNMkmQoCcIR4ENFx71YAGEMNCQ318Nzef1SN4syyGAqNHOsMDNFccAsAtwxNb1Vx5NOElNcN_oNNiN98JB50Q1h8VgzpsAGwdMDMjlD030qKr0RmwQ9JSt2Ap1FcVMeiXNUNZNn1_NP1Qt_1JsjhDIlU4R1ItIThTISBrIleNRvw3pVAfCJQd4ZQmQOQeQlMdwdM1o-J7-jBcWnQtoLQVgABAAioovQUHYFLwFpuHA0jlK2J6g6j6o_OQPpUDDANJH5LlHlKAFjLlAAKQBTO4igWqtLIgpRGAZ3lqbQ51SR50F0KTJBl2O4ij-111Z0PS6LPC4QNRMAYy5Ql30xAxX5qBEJ-TD2j05y07eDSh-SN1j1PojBSSYQ6BdEVJ-TeEr2uTOmo4BBUkPDaSD1lYGx3AC571nCwCmbYAwAIB-St2wBj1AzSzOiujJH8goApTig6SYQIBGA2UcaN0b2Q4-J-STDtKHATXl3vBMqmB7yZ2bR93MAD3T0j2l05wT1T1D2YPX38Q8gL3UlMDL05ygOb3iDb3SAIAEMH28i8Qogn0sR-TdiX24QEO32ZAP3wBP13ov2BRkxBRAA&debug=false&evaluate=false&experimental=false&lineWrap=true&loose=false&presets=es2015%2Creact%2Cstage-2&prettier=false&spec=false&targets=) where it would be lazy-loaded only if requested. I ended up using [bundle.run/prettier](https://bundle.run/prettier@1.5.3) instead so I'll close this issue.
